version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      TZ: ${TZ}
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/var /var/www/html/src/core/http/../../cache &&
             chmod -R 775 /var/www/html/var /var/www/html/src/core/http/../../cache &&
             apache2-foreground"
    volumes:
        - .:/var/www/html
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
