<?php

namespace DoctrineProxies\__CG__\Src\entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Roles extends \Src\entities\Roles implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'users' => [parent::class, 'users', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
